### ISSUE TITLE
Implement network toggle switch 

### ISSUE THREAD

**Issue by rmilrad** [hemilabs/CryptoChords#83]
Implementation of the network toggle switch for testnet / mainnet viewing.

**Comment by rmilrad** [comment]
@rafappelt Is this complete? I recall you may have started on this but can't remember. Perhaps were just waiting for mainnet endpoints to finalize and publish?

**Comment by rafappelt** [comment]
@rmilrad It is not started.
@dvnahuel do we have any design / figma for it?

**Comment by rmilrad** [comment]
https://www.figma.com/design/4fVd9wneclsvYDYD95ApZ9/Hemi-Portal?node-id=4532-4741&t=qUsQPkbTUOGnzA6a-1 @rafappelt
